services:
  mongodb:
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${PMLIBS_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${PMLIBS_PASSWORD}
    volumes:
      - './database/data:/data/db'
    ports:
      - '27017:27017'
  api:
    build:
      context: ./pmlibs-api
      dockerfile: Dockerfile
      args:
        DOMAIN: ${DOMAIN}
    environment:
      - CONNECTION_STRING=mongodb://${PMLIBS_USERNAME}:${PMLIBS_PASSWORD}@mongodb:27017/
      - CONNECTION_DATABASE=library
    container_name: api_container
    depends_on:
      - mongodb
    links:
      - mongodb
    ports:
      - '5000:5000'
  cors:
    build:
      context: ./cors
      dockerfile: Dockerfile
    container_name: cors_container
    ports:
      - '8080:8080'
  app:
    build:
      context: ./pmlibs-vue
      dockerfile: Dockerfile
    container_name: vue_app_container
    ports:
      - '80:80'
      
    